Load ToC and Privacy Policy through pdf documents
maxgala/aspire-frontend pull request #146
Opened 2020-09-05 04:17 UTC by ahmedhamodi

close #121

2020-09-09 03:24 UTC, arsidada requested changes
@ahmedhamodi can you post screenshots for the before and after so we can visually review the change

2020-09-13 03:13 UTC, ahmedhamodi commented on src/Components/Registration/FinalPage.js
> +pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;
The PDF file fails to load if that cdn isnt included/working:
![image](https://user-images.githubusercontent.com/13268990/93009276-e5cda280-f54c-11ea-8cdb-db01bc74ea10.png)

How do you recommend we work around this? The main solution I found online is to use this pdf worker.

2020-09-14 04:05 UTC, mohaimenhasan approved these changes
Looks good to me !!

2020-09-14 17:40 UTC, ahmedhamodi commented
Can you re-review @arsidada?

Here are the before/after pictures you requested.

Before:
![image](https://user-images.githubusercontent.com/13268990/93119381-b4112480-f68f-11ea-8713-aaa9105d2cc7.png)

After:
![image](https://user-images.githubusercontent.com/13268990/93119425-c7bc8b00-f68f-11ea-86f6-15f1f8dab5ec.png)

2020-09-16 00:46 UTC, arsidada approved these changes

2020-09-16 00:47 UTC, merged