Ammar admin job boards
maxgala/aspire-frontend pull request #231
Opened 2020-11-20 01:19 UTC by ahaq0

Add a job board to enable admin to view, search and delete all jobs created.

2020-11-20 01:31 UTC, arsidada commented
@ahaq0 build is failing. likely because of an import that wasn’t committed to package.json

2020-11-20 01:45 UTC, ahmedhamodi commented
In particular, the material-table component:
![image](https://user-images.githubusercontent.com/13268990/99747155-365f0000-2aa8-11eb-8d21-04ef9af969b2.png)

2020-11-20 01:48 UTC, ahmedhamodi reviewed
A few comments! Overall, looks good. I'll do a more detailed test (ie. run the app and test) later.

2020-11-20 01:48 UTC, ahmedhamodi commented on src/Components/Admin/JobPosts.js
> +    console.log(existingJobsData);
Remove console log

2020-11-20 01:48 UTC, ahmedhamodi commented on src/Components/Admin/JobPosts.js
> +    // The job is already removed from state, so we just send the PUT request to remove it
Remove console log. Also, misplaced comment? Should be above the PUT request (or removed)

2020-11-20 01:48 UTC, ahmedhamodi commented on src/Components/Admin/JobPosts.js
> +    console.log(this.state);
Log!

2020-11-20 01:48 UTC, ahmedhamodi commented on src/Components/Admin/JobPosts.js
> +        pageSizeOptions:[5,10,15,30,50]
I'd be a fan to include an export button. In material table you can do:
`exportButton: true,
exportAllData: true`

2020-11-20 15:16 UTC, arsidada requested changes
fix import change

2020-11-21 01:45 UTC, ahaq0 commented on src/Components/Admin/JobPosts.js
> +    console.log(existingJobsData);
oops sorry was too excited after we figured out the issue, I didn't look it over prior to making the PR.

2020-11-21 02:07 UTC, ahmedhamodi commented on src/Components/Admin/JobPosts.js
> +        exportAllData: true
Should be: exportButton: true, exportAllData: true
not exportTrue

2020-11-21 03:11 UTC, ahmedhamodi commented
Not sure why the build is failing. Does it run locally for you @ahaq0 ?

2020-11-21 03:41 UTC, arsidada approved these changes

2020-11-21 03:41 UTC, ahmedhamodi approved these changes
Yay it passed!!

2020-11-21 03:43 UTC, merged