Promote to prod
maxgala/aspire-frontend pull request #422
Opened 2021-11-06 14:15 UTC by NabaSadiaSiddiqui

2021-11-06 19:12 UTC, ashaduzzamane reviewed
Change the image file name into something more descriptive

2021-11-07 19:50 UTC, tahbibO commented on src/Components/Dashboard/Cards/CommunityCard.js
> +            {"Accept Connection?"}
This should be Send Request

2021-11-07 19:52 UTC, tahbibO commented on README.md
> +# aspire-Frontend
fix small grammar and spelling errors

2021-11-07 20:20 UTC, tahbibO requested changes
- update readme to fix mistakes
- change connection request header to "send connection"

2021-11-07 20:58 UTC, tahbibO approved these changes

2021-11-10 18:01 UTC, tahbibO approved these changes

2021-11-10 18:15 UTC, merged